### PR TITLE
Scott Madeira - Project Submission

### PR DESCRIPTION
**Pull request by smadeira**
Josh,

Here is my answer.  Looking forward to your feedback and thoughts. The "random change generator" was an interesting twist! If you have any questions let me know.  To run the code so a php start.php input.txt

Scott

### CODE REVIEW

**Comment by smadeira** [comment]
Two other thoughts (just so you know I didn't miss them)

1, I didn't do anything with namespaces here.  In a real application and a real framework that would be important to do.  But for this exercise, I didn't include it.

2. The Denomination classes - I took them all the way to $20 and if I was going to do another pass at refactoring this, I would probably create abstract penny, nickel, etc. classes and then have standard and random penny, nickel, etc. classes extend the abstract classes.  The code as submitted has some duplicate code in these classes but for the purposes of the exercise I chose that instead of adding another 8 or so classes to the project.

**Comment by smadeira** [comment]
Made changes for fix a bug I thought of overnight.  Will submit a new pull request.

**Comment by smadeira** [comment]
Sorry for all the back and forth...  Thought of a bunch of things in the shower this morning and committed all my changes.  Have an awesome day!

**Comment by jgretz** [comment]
code received and being reviewed

**Comment by jgretz** [comment]
And thanks for all the flavor text :)

**Pull request closed without merging**
